In [1]:
# Import Pandas
import pandas as pd

In [2]:
# Read CSV
london_airbnb_listings = pd.read_csv(r'C:\Users\kpali\Documents\Projects\London_Airbnb_Search\listings.csv', delimiter = ',', encoding = 'utf-8')
london_airbnb_listings.head()

,name,neighbourhood_cleansed,room_type,accommodates,bedrooms,bathrooms_text,amenities,minimum_nights,maximum_nights,price,host_response_time,review_scores_value,listing_url
0,Holiday London DB Room Let-on going,Islington,Private room,1,1.0,1 shared bath,"[""Board games"", ""Conditioner"", ""Freezer"", ""Sho...",1,29,$79.00,within a day,4.71,https://www.airbnb.com/rooms/13913
1,Bright Chelsea Apartment. Chelsea!,Kensington and Chelsea,Entire home/apt,2,1.0,1 bath,"[""Smoke alarm"", ""Long term stays allowed"", ""Wa...",10,50,$75.00,within a few hours,4.74,https://www.airbnb.com/rooms/15400
2,Nice double bedroom in NW London,Camden,Entire home/apt,2,2.0,NaN,"[""TV with standard cable"", ""Long term stays al...",21,365,$229.00,NaN,NaN,https://www.airbnb.com/rooms/172811
3,The Residential Suite Above Gallery,Hackney,Entire home/apt,3,1.0,1.5 baths,"[""Cleaning products"", ""Ceiling fan"", ""Stainles...",2,31,$132.00,within an hour,4.71,https://www.airbnb.com/rooms/173082
4,You Will Save Money Here,Barnet,Private room,2,1.0,1 shared bath,"[""Fire extinguisher"", ""Hot water"", ""Shampoo"", ...",4,365,$65.00,within a few hours,4.87,https://www.airbnb.com/rooms/42010

In [3]:
# Remove all rows that contain null values
london_airbnb_listings.dropna(how = 'any', inplace = True)
# Remove text in bathrooms_text + remove any null cells + convert to float
london_airbnb_listings['bathrooms_text'] = london_airbnb_listings['bathrooms_text'].str.replace(r'[^0-9\.]+', '')
london_airbnb_listings['bathrooms_text'] = london_airbnb_listings['bathrooms_text'].replace('',pd.NA)
london_airbnb_listings = london_airbnb_listings.dropna(subset = ['bathrooms_text'])
london_airbnb_listings['bathrooms_text'] = london_airbnb_listings['bathrooms_text'].astype(float)
# Remove $ from price + convert to float
london_airbnb_listings['price'] = london_airbnb_listings['price'].astype(str)
london_airbnb_listings['price'] = london_airbnb_listings['price'].str.replace(r'[\$,]','')
london_airbnb_listings['price'] = london_airbnb_listings['price'].astype(float)
# Rename columns + capitalise first letter of each word
london_airbnb_listings.rename(columns = {'neighbourhood_cleansed':'neighbourhood', 'bathrooms_text':'bathrooms',
'review_scores_value': 'rating', 'room_type':'room type','minimum_nights': 'minimum nights',
'maximum_nights': 'maximum_nights', 'host_reponse_time': 'host response time', 'listing_url': 'listing url'},inplace = True)
london_airbnb_listings.columns = london_airbnb_listings.columns.str.title()
# Check null values have been removed
print((london_airbnb_listings.isnull().any(axis = 1)).sum())
# Preview Columns
london_airbnb_listings.head()

0

C:\Users\kpali\AppData\Local\Temp\ipykernel_21356\804524731.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  london_airbnb_listings['bathrooms_text'] = london_airbnb_listings['bathrooms_text'].str.replace(r'[^0-9\.]+', '')
C:\Users\kpali\AppData\Local\Temp\ipykernel_21356\804524731.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  london_airbnb_listings['price'] = london_airbnb_listings['price'].str.replace(r'[\$,]','')

,Name,Neighbourhood,Room Type,Accommodates,Bedrooms,Bathrooms,Amenities,Minimum Nights,Maximum_Nights,Price,Host_Response_Time,Rating,Listing Url
0,Holiday London DB Room Let-on going,Islington,Private room,1,1.0,1.0,"[""Board games"", ""Conditioner"", ""Freezer"", ""Sho...",1,29,79.0,within a day,4.71,https://www.airbnb.com/rooms/13913
1,Bright Chelsea Apartment. Chelsea!,Kensington and Chelsea,Entire home/apt,2,1.0,1.0,"[""Smoke alarm"", ""Long term stays allowed"", ""Wa...",10,50,75.0,within a few hours,4.74,https://www.airbnb.com/rooms/15400
3,The Residential Suite Above Gallery,Hackney,Entire home/apt,3,1.0,1.5,"[""Cleaning products"", ""Ceiling fan"", ""Stainles...",2,31,132.0,within an hour,4.71,https://www.airbnb.com/rooms/173082
4,You Will Save Money Here,Barnet,Private room,2,1.0,1.0,"[""Fire extinguisher"", ""Hot water"", ""Shampoo"", ...",4,365,65.0,within a few hours,4.87,https://www.airbnb.com/rooms/42010
5,Superb 3-Bed/2 Bath & Wifi: Trendy W1,Westminster,Entire home/apt,6,3.0,2.0,"[""Cleaning products"", ""Clothing storage: close...",4,365,425.0,within a few hours,4.60,https://www.airbnb.com/rooms/17402

In [4]:
london_airbnb_listings.to_csv('../listings.csv',index = False)